### ISSUE TITLE
Consult with editorial about overall interface

### ISSUE THREAD

**Issue by katinalynn** [mlaa/cbox-mla#124]
Opening this as an issue so that it remains on the horizon: We've discussed doing a thorough review of the Commons interface in consultation with editorial. Discuss consistency, clarity of hierarchies, adherence to MLA style. (See also https://github.com/mlaa/cbox-mla-blog/issues/8)

**Comment by JonathanReeve** [comment]
Moving this to 3.0, since that will be the best time for running design, copy, etc, through editorial.

**Comment by chriszarate** [comment]
Closing individual ed. issues in favor of future periodic review.
