### ISSUE TITLE
private groups with more than seven members require login to view their landing pages

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#139]
It seems only certain private groups are requiring login--I can access the landing page of the nominating committee while logged out, for instance, and the private group "msa2014pedagogy," but not the ADFL Executive Committee or the private non-committee Arabic Editorial Board.

**Comment by JonathanReeve** [comment]
Could it be that somehow the forums for these groups are private, and require login, while the groups themselves aren't?

**Comment by JonathanReeve** [comment]
Putting this off.

**Comment by chriszarate** [comment]
No longer an issue.
