### ISSUE TITLE
enable Invite Anyone and rename tabs in translations

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#141]
Is this a bug or a feature? I think we might need more people to weigh in on this one. On one hand, I can see that it'd be good to be able to invite members to your group without necessarily adding them as a contact first. On the other hand, I can see how we might want to protect invitees from getting spammed with lots of unwanted invites.

**Comment by JonathanReeve** [comment]
Looks like it was [Invite Anyone](https://wordpress.org/plugins/invite-anyone/). I can test this again and see if it's practical to reenable it, or submit a feature request upstream for typeahead capability.

**Comment by JonathanReeve** [comment]
The latest version of Invite Anyone has a typeahead member search feature. It's prohibitively slow on a VM, but works reasonably well on AWS, with a lag of only a couple of seconds. There are a few issues that would need to be solved first in order to enable this, however: 

![selection_456](https://cloud.githubusercontent.com/assets/1843676/5646997/e0c1334a-964f-11e4-95ce-9617d905cf24.png)

 * somehow consolidate the tabs "Invites" and "Send Invites." This could be as easy as disabling the native BuddyPress version. 
 * stop "Send Invites" from displaying the message "Select people to invite from your contacts list."

**Comment by JonathanReeve** [comment]
The above two issues aren't happening on a vanilla CBOX install, so it must be something in the theme.

**Comment by JonathanReeve** [comment]
Putting this off for the moment.

**Comment by terrainsvagues** [comment]
Let's discuss at our 01/13 meeting. Lots of people complaining about how counter-intuitive and off-putting this is at the Convention.

**Comment by terrainsvagues** [comment]
I'm not sure we'd want"Send Invites" NOT to display the contacts list / select people to invite message. There should be a typeahead option and a select contacts option, so that people can quickly add multiple contacts if they prefer.

**Comment by chriszarate** [comment]
Note from conversation with JR: Can we disable fetching autocomplete results until the user has typed two or three characters? Would probably improve responsiveness.

**Comment by JonathanReeve** [comment]
This is a tough one. I can't quite seem to figure out why we're still seeing both "Invites" and "Send Invites." 

![selection_479](https://cloud.githubusercontent.com/assets/1843676/5859242/e015098e-a226-11e4-8052-63b401cb68a5.png)

It must be a setting somewhere, since disabling all plugins and switching the theme to cbox-theme doesn't seem to fix it.

**Comment by JonathanReeve** [comment]
@boonebgorges, any ideas why Invite Anyone might be producing these double tabs? I thought it must be one of our customizations, but I'm still seeing this behavior after switching to a vanilla theme and disabling all other plugins.

**Comment by boonebgorges** [comment]
@JonathanReeve What are the URLs of the Invites and the Send Invites steps? I have a feeling that one is being caused by Invite Anyone (URL will contain `invite-anyone`), and the other coming from BP (`send-invites`, I think).

**Comment by JonathanReeve** [comment]
@boonebgorges, `Invites` is at `groups/create/step/group-invites/`, and `Send Invites` is indeed `groups/create/step/invite-anyone/`. I can't quite seem to figure out why double invite tabs appear on our install, but not on a vanilla CBOX install. I'll keep digging into this.

**Comment by boonebgorges** [comment]
If it helps, here's what's happening from the IA point of view. BP adds 
a 'group-invites' menu item. IA should remove it and replace it with 
'invite-anyone'. Here's the relevant function: 
https://plugins.trac.wordpress.org/browser/invite-anyone/trunk/group-invites/group-invites.php#L453 
As you can see, there are a few places where the removal could bail or 
fail. My guess is that you have configured the Invite Anyone settings in 
such a way that the `invite_anyone_group_invite_access_test()` check is 
being incorrectly tripped, which probably indicates a logic issue in IA, 
but it's hard to guess what it is without knowing more about your setup. 
If you track this down, let me know - it's almost certainly an IA bug.

**Comment by JonathanReeve** [comment]
Thanks! I'll look into those functions.

**Comment by JonathanReeve** [comment]
This bug might be a feature, since "Invites" takes care of inviting one's contacts, and "Send Invites" takes care of inviting anyone else. If we rename these tabs to "Invite Contacts" and "Invite Others," then we effectively solve this problem. I'll edit the title of this bug to reflect this.

**Comment by JonathanReeve** [comment]
I like that Invite Anyone adds a new step to group creation that allows users to invite non-contacts, and that effectively solves this issue, which was originally that users couldn't invite non-contacts. But I'm starting to think that the side-effect of enabling Invite Anyone--the new user profile tab "Send Invites," which allows users to invite anyone by email--is maybe undesirable for our purposes: 

![selection_520](https://cloud.githubusercontent.com/assets/1843676/6755264/26f6b2fa-cef8-11e4-8f26-e6e9d6f55fef.png)

If we enable Invite Anyone, but stop it from adding this new profile tab (highlighted in red above), then we can avoid having to do #231, and it keeps everything nice and simple. This way, users won't (I don't think) be able to invite non-members by email, which saves us from having to handle that use-case. 

Also, disabling the profile tab would also solve the problem of the translatability of the string "Send Invites," which, if we were to translate it to "Invite Others," would also change the title of this profile tab, which would look a little out-of-place.

**Comment by boonebgorges** [comment]
Try running `bp_core_remove_subnav_item( bp_get_current_group_slug(), 
'invite-anyone' )` (or something like that) before the page is rendered.

**Comment by JonathanReeve** [comment]
Thanks, Boone! I'll give that a shot.

**Comment by JonathanReeve** [comment]
I was able to remove the tab with 93e7930.

**Comment by JonathanReeve** [comment]
It turns out that renaming "Invites" -> "Invite Contacts" and "Send Invites" -> "Invite Others" is more complicated than it seems. I can't find a way to translate "Send Invites" without also changing that text in the group tab, and translating "Invites" is also more complicated than it looks. I actually don't terribly mind the text "Invites" .. "Send Invites" now, because it's technically correct--the invites seem to accumulate from the first of these steps to the second, and the second seems like it sends them.

**Comment by JonathanReeve** [comment]
This one is ready for testing on Sinclair.

**Comment by JonathanReeve** [comment]
If there are no other ideas about renaming these tabs, I'll keep this one as-is, and close this issue.
