### ISSUE TITLE
rename 'profile' to 'portfolio' in slugs

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#146]
See #133 and commit 479dbdb1484ccbe5d98561acf299e46097c06f67 which breaks everything. This one will be a little tricky.

**Comment by terrainsvagues** [comment]
I would actually like to discuss the use of "portfolio" when we don't actually offer members a place in the portfolio area to upload their work. It really seems more of a "profile" as it currently stands.
