### ISSUE TITLE
Enforced HTTPS

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla#163]
We will consider enforcing HTTPS/TLS for every request (not just authentication and admin). The arguments for this practice have been laid out many times (recently by the [Times][0]).

Many of the typical arguments against do not necessarily apply to us, but a few may:

1. Increased CPU/memory overhead. This has been shown to be greatly exaggerated and is primarily related to the initial handshake. Google, in particular, has noted that this overhead is in fact marginal.

2. Increased latency (time-to-first-byte). The initial handshake requires a couple of roundtrips to the server. This is probably the most concerning factor; however, we probably have several places where we could optimize in excess of any added latency.

Assigning to me.

[0]: http://open.blogs.nytimes.com/2014/11/13/embracing-https/

**Comment by chriszarate** [comment]
We are obtaining wildcard certs, should have them early February.

**Comment by JonathanReeve** [comment]
I think we can close this one, right?

**Comment by chriszarate** [comment]
Yup, thanks.
