### ISSUE TITLE
strange behavior when replying to group activity posts

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#167]
Katherine reports that replies to group activity items don't display correctly the first time: 

![site-wide_activity_-_mla_commons clipular_360](https://cloud.githubusercontent.com/assets/1843676/5150058/0692e460-719d-11e4-8b3c-78fd59e0847f.png)

As I understand it, the process to reproduce is this: 

1. in commons.mla.org/activity, write an update, and post it to a group. 
2. in that group's activity stream, reply to that newly-created activity item. 
3. mysterious things happen. 

I can't reproduce it yet, but recording this here in case anyone else can. Tested on the latest Chromium (Linux), Chrome (Windows), and Firefox (Linux).

**Comment by chriszarate** [comment]
Cannot reproduce.
