### ISSUE TITLE
Groups Directory facets/filters are sticky between tabs, across site, and across sessions

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla#176]
This may be a `cbox-theme` or `cbox` bug, and may also extend to other BP constructs like members, sites, activity items, etc.

To replicate:

1. Visit the Groups Directory: http://commons.mla.org/groups/.
2. Adjust the filters to show a small subset of groups (e.g., Type: Prospective Forums).
3. Optionally: close the tab and return hours, days, or weeks later.
4. Visit your Commons activity page and select My Groups.
5. The Groups section will apply the filters you chose on the Groups Directory page. Often—and especially if you belong to a small number of groups—this results in a message saying "There were no groups found." There is no way on this page to adjust the filters or even see that filters are being applied.

This issue also applies (perhaps to a lesser degree) to the "My Groups" tab on the Groups Directory page. The filters are "sticky" between the two. While the user has the ability here to see and adjust the filters, this may still be contrary to expectation. The user has clicked an action item that says "My Groups" but receives results that vary based on previous actions—perhaps even from a previous browsing session days earlier.

Is the expected behavior instead that these filters apply only to the immediate context, and "reset" whenever the user navigates away (even to a tab on the same page)?

If we can replicate on vanilla CBOX, let's file upstream.

**Comment by JonathanReeve** [comment]
So I'm thinking that we want to have filters persist when a user clicks the browser's "back" button, but not under any other circumstances.

**Comment by terrainsvagues** [comment]
This is still an issue. Carol reports (and I confirm) that search filters (both 'my' and any other search term) do not stick when one tabs through pages of member, group, or directory.

**Comment by chriszarate** [comment]
Not the original issue, but probably related to the fix. Are we still considering infinite scroll for these contexts? If so, may want to move to 3.0.
