### ISSUE TITLE
Previously selected options are not respected when using back button on browser

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#182]
Sort all members by newest registered.
Go to any results page other than the first.
Click on a member name to view their portfolio. 
Click the back button on your browser.
You end up at the first page rather than the page you were last on.

This was also happening earlier (although I cannot reproduce now) with members sorted by 'most recent'. I was browsing the list of 'all members,' but once I clicked on a name and then clicked the back button on my browser, I was repeatedly brought into 'my contacts' rather than 'all members' whence I came.

**Comment by JonathanReeve** [comment]
This is probably related to #176, and likely has something to do with what filters are getting stored in what cookies. Slating for Epistolary, somewhat optimistically.

**Comment by terrainsvagues** [comment]
Part A is definitely a replica of #195, but the 'all members' / 'my contacts' issue is separate but related.

**Comment by JonathanReeve** [comment]
Per our discussion on Slack and @chriszarate's suggestions, there might be a few ways of doing this:  
 * URL hashes, although this would make the URL much messier-looking than it currently is
   - maybe using a library like https://github.com/cowboy/jquery-bbq
 * hijacking links that leave directories and making them appear in a modal or iframe (https://github.com/artsy/scroll-frame) 
 * using Backbone.js history, which could come in handy for other things, too.  

Obligatory XKCD: 

![infinite_scrolling](https://cloud.githubusercontent.com/assets/1843676/5671214/1844ee60-9754-11e4-9ffd-4c99ff9e36b2.png)

Which is actually not a bad idea. If we can solve this issue, and it isn't too tricky to implement infinite scrolling, it might be a nice feature. That way we could get rid of pagination altogether. I'll open a wishlist / question item for it.

**Comment by JonathanReeve** [comment]
Putting this off for the moment, pending more discussion.

**Comment by JonathanReeve** [comment]
Putting this off again.
