### ISSUE TITLE
group forum visibility should change along with group visibility

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#189]
Use case: a group starts off hidden, but becomes public once it's ready. That group's forum is hidden, but doesn't become public when its parent group becomes public. 

Test on a vanilla CBOX install and submit a bug report upstream if applicable.

**Comment by JonathanReeve** [comment]
There's some work on this one over at https://bbpress.trac.wordpress.org/ticket/2599.

**Comment by chriszarate** [comment]
Fixed in BP 2.6, but will need to wait for it to be released. Thanks @JonathanReeve for reporting!
