### ISSUE TITLE
Provide link to Guidelines for Participation in footer

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#192]
Perhaps we can replace the link to the user voice site with one to the [Guidelines for Participation](http://commons.mla.org/guidelines/), as these are impossible to find on the site.

**Comment by JonathanReeve** [comment]
I'll just copy the cbox-mla footer into cbox-mla-blog theme, since the Commons footer has the link to the Guidelines. Cbox-mla-blog 3.0 needs this, and it could be worth fixing this in 2.0, too, since it'll be a while before 3.0 is released.

**Comment by JonathanReeve** [comment]
Moved to mlaa/cbox-mla-blog#29 and mlaa/cbox-mla-blog#30.
