### ISSUE TITLE
add stepped progress indicator to avatar changing sequence

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#194]
At the moment, changing one's avatar is a little confusing for some users. It's a multi-step process (browse, upload, crop, save), but that isn't well-indicated. This has led one user to wonder what to do if she doesn't want to crop her avatar, and how to save her avatar from the crop screen. Adding a step-based progress indicator [like the first one here](http://www.hongkiat.com/blog/progress-bar-designs/) would mitigate this issue somewhat. 

    (1. Upload) >>>>>>>>> (2. Crop) >>>>>>>>>>> (3. Save)

**Comment by chriszarate** [comment]
Moving to wishlist.
