### ISSUE TITLE
use progress tracker for Create a Group sequence

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#196]
The current UI, based on tabs, doesn't work when the tabs wrap, and should probably be a progress tracker instead. 

![selection_455](https://cloud.githubusercontent.com/assets/1843676/5646894/f4785fd6-964e-11e4-9b29-5491e3cd86bb.png)

The [ones at Atlassian](https://design.atlassian.com/2.1/product/patterns/progress-tracker/) look pretty good. Slating for 2.3.0, since this is a good candidate for inclusion in the style guide.

**Comment by JonathanReeve** [comment]
See also #194.

**Comment by JonathanReeve** [comment]
Putting this off until 3.0, because it seems non-trivial, and could benefit from a design discussion and/or stylesheet.

**Comment by terrainsvagues** [comment]
I would like to see this kind of tracker for Create a Site too. And onboarding. Will make an issue.
