### ISSUE TITLE
Create a Group email default is confusing

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#200]
We say that "No Email" is "the default," but the radio button next to "All Email" is the one that is selected by default.

![screen shot 2015-01-07 at 1 29 20 pm](https://cloud.githubusercontent.com/assets/7083891/5650973/60e10c96-9671-11e4-98dc-78279a50cdae.png)

**Comment by JonathanReeve** [comment]
This is confusing, indeed. It looks like this is also the default setting on a stock CBOX install. I feel like the thing to do would be to set it to Daily Digest. (I thought it already was, for some reason.) Then group admins would have the option of changing this as they see fit. @chriszarate, what do you think?

**Comment by JonathanReeve** [comment]
^ Submitted upstream at cuny-academic-commons/commons-in-a-box#106.

**Comment by JonathanReeve** [comment]
Putting this on hold for now, awaiting an upstream fix. Overriding this text in a translations file in `wp-content/languages/buddypress-group-email-subscription` isn't taking effect as it should--maybe its textdomain isn't set up properly?

**Comment by JonathanReeve** [comment]
Submitted the related issue of BP-GES untranslatability upstream at boonebgorges/buddypress-group-email-subscription#67.

**Comment by chriszarate** [comment]
Issue fixed upstream.
