### ISSUE TITLE
infinite scrolling? 

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#201]
This would be a neat feature, and if we could implement it in a way that would work well with browser "back" buttons, it would solve pagination issues like #195. Maybe this could be an idea for a completely rewritten 3.0 version.

**Comment by terrainsvagues** [comment]
Let's prioritize this, at least for the homepage, for 3.0

**Comment by JonathanReeve** [comment]
Yeah! I like it. This would probably require some AJAX magic, but would be well worth it, IMO. Starting a 3.0 milestone to put these new plans.

**Comment by terrainsvagues** [comment]
Awesome sauce. If we could make the homepage more vertical, with big sexy categories of content, rather than blocky as it is now, that would be pretty sweet too.

**Comment by JonathanReeve** [comment]
+1 for vertical and non-blocky, absolutely.

**Comment by kfitz** [comment]
Leaving this comment in the right spot: A vertical/scrolling front page I'm fond of: http://digitalarchaeology.msu.edu

**Comment by JonathanReeve** [comment]
@kfitz, I love pages like that. I'd love to see the Commons get a design treatment somewhat along those lines.

**Comment by terrainsvagues** [comment]
OMGZ yes. 
http://premium.wpmudev.org/blog/how-to-add-infinite-scrolling-to-your-wordpress-site/ (just putting this here for ref)

**Comment by JonathanReeve** [comment]
Looks like backbone.js integration simplifies this process:  

http://wptavern.com/_s_backbone-a-wordpress-starter-theme-based-on-underscores-and-backbone-js

Something to think about for 3.0.

**Comment by JonathanReeve** [comment]
Looks like there's a plugin: https://github.com/bphelp/bp-auto-load-activity.

**Comment by JonathanReeve** [comment]
The plugin works with twentyfifteen, and partially works with cbox-mla, but isn't working on 3.0. It could probably be adapted, though. Maybe it'd be nice to use a jQuery plugin like [jscroll](http://jscroll.com/).
