### ISSUE TITLE
CFP / announcements plugin?

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#211]
Here's an idea for a top-level "add" button: 

![selection_469](https://cloud.githubusercontent.com/assets/1843676/5710390/a93b67aa-9a6f-11e4-8101-dfb97c708f18.png)

Maybe hovering over it could reveal a tooltip that says "post something." Clicking on this button would take you to a page probably called Post. It might look something like this: 

![selection_470](https://cloud.githubusercontent.com/assets/1843676/5710842/7a7503aa-9a73-11e4-9571-25e905d420d1.png)

with "Post Type" options being "Call for Papers," "Call for Participation," "Fellowships and Grants," etc. 

There might also be additional fields for "Conference Date," "Submission Deadline," etc, with date pickers. 

The resulting submissions could be stored as custom post types, which could then be approved or flagged as spam.

**Comment by JonathanReeve** [comment]
But now that I think of it, the "+" button doesn't really follow our current paradigm. To add a group, it's Groups -> Create a Group, and to add a site, it's Sites -> Create a Site, so it would follow that to create a CFP, it'd be more like CFPs -> Post a CFP. The CFPs page would then list all CFPs, organized by deadline, and would feature a button for adding one.

**Comment by chriszarate** [comment]
Moving to wishlist with a link back to this issue for future reference.
