### ISSUE TITLE
Add twitter feed of members

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#212]
See [CUNY Academic Commons] (http://commons.gc.cuny.edu/twitter/). See [twitter list] (https://twitter.com/MLACommons/lists/mla-commons-members) in progress.

**Comment by JonathanReeve** [comment]
Cool. Looks like we have 986 twitter usernames on record, so that should be interesting. And CUNY has [very kindly posted their code](https://github.com/cuny-academic-commons/cac-twitter-stream).

**Comment by terrainsvagues** [comment]
Awesome! @JonathanReeve Could you direct me to those 986 twitter handles? Would make my list curation much easier! Thx.

**Comment by JonathanReeve** [comment]
I have a list of the twitter user names from the database, but the table itself doesn't contain a column for whether that user has made that information public, private, or only visible to contacts. The visibility data is stored elsewhere in the DB (in a rather cryptic way, it looks like), so to get a list of only those Twitter user names which have been made public, I might have to write a little script to loop through them.

**Comment by terrainsvagues** [comment]
I've done this using the Twitter widget in the footer of the community site. Not all members by any means, as I had to make a Twitter list by hand.

**Comment by JonathanReeve** [comment]
I could do this with a little light database programming, I think. 
 1. check to see if anyone at all lists a _Twitter_ username but makes it private or only visible to contacts. If not, I've saved myself a lot of work. 
 2. if there are some, note those
 3. get a list of all _Twitter_ username fields except for those from members from step 2.

**Comment by JonathanReeve** [comment]
Slating for Sentimental, since I think this would be fun.

**Comment by JonathanReeve** [comment]
I realize now why I couldn't do this very easily before. Xprofile visibility levels are encoded in a really obscure way, such that the MySQL query: `select meta_value from wp_usermeta where meta_key='bp_xprofile_visibility_levels'` returns entries like: 

    a:7:{i:1;s:6:"public";i:3;s:6:"public";i:2;s:6:"public";i:4;s:6:"public";i:8;s:6:"public";i:5;s:6:"public";i:7;s:6:"public";}

So I think I'd have to write a PHP script to do this.

**Comment by JonathanReeve** [comment]
Putting this off until the next release, since it's turned out to be more complicated than I thought.

**Comment by JonathanReeve** [comment]
Tried this in 69d3977...fef77a2, but it keeps running the server out of memory. I don't want to spend too much time on this at the moment. But it's getting there.

**Comment by chriszarate** [comment]
Added to wishlist.
