### ISSUE TITLE
remove group admin option to change the group's discussion board

### ISSUE THREAD

**Issue by kshkim** [mlaa/cbox-mla#219]
As an admin (Katherine's public groups) when I click my group / manage / discussion, I have the option to set other groups as my group discussion board: 

![practice - manage - mla commons clipular](https://cloud.githubusercontent.com/assets/8835589/5822544/fc420a88-a0a2-11e4-884f-c989890a99c3.png)

(This doesn't matter if the option will be removed, but the language in the drop down menu still uses "forum" instead of "discussion")

**Comment by JonathanReeve** [comment]
Good catch. We should probably remove this option. Giving users the ability to change their group's forum seems unnecessary and confusing. I'll edit the title of this issue to reflect that.

**Comment by JonathanReeve** [comment]
Putting this off. I am tempted to just remove this line entirely in the template, but I know that sometimes form submissions depend on these things being there.

**Comment by chriszarate** [comment]
Only super admins see this option.
