### ISSUE TITLE
clarify language of default privacy options during group blog creation

### ISSUE THREAD

**Issue by kshkim** [mlaa/cbox-mla#220]
![create a group - mla commons clipular](https://cloud.githubusercontent.com/assets/8835589/5842656/876a220e-a174-11e4-8a99-c3ce3b3390c0.png)

Am setting up a practice group, and the privacy options for the group blog seem unclear. Perhaps a sentence that clarifies the purpose of not clicking one of those bottom options (Visible only to registered users of this network; Visible only to registered users of this site; Visible only to administrators of this site)? @terrainsvagues, what do you think would be best?

**Comment by chriszarate** [comment]
Looks like an issue with `more-privacy-options`. Should we fix or will this be mitigated with better group creation flow?

**Comment by chriszarate** [comment]
Closing in favor of revamping group creation flow (wishlist).
