### ISSUE TITLE
page <title> for individual messages says "page 123" instead of "message 123"

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#221]

**Comment by JonathanReeve** [comment]
@terrainsvagues reports that page titles say "page 123" when they should probably be saying "message 123." Screenshot: 

![screen_shot_2015-01-29_at_11 11 07_am_360](https://cloud.githubusercontent.com/assets/1843676/5961255/5c0a63ae-a7a9-11e4-988e-a6b1670f0479.png)

**Comment by modelm** [comment]
sort-of-but-not-really-related upstream bug: https://buddypress.trac.wordpress.org/ticket/6107

I went ahead and fixed this in the theme with a filter for now, but a more robust fix should probably make its way upstream at some point.
