### ISSUE TITLE
new docs have commenting disabled by default

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#224]
Despite the visibility / permissions controls all displaying the correct permissions, new docs appear to have commenting disabled. These docs have DB values of `comment_status` set to `closed`. This seems to happen both on a fresh, vanilla buddypress-docs install, and on our fork. 

I'm leaving this issue in this repo, since it seems like it might be a problem with our theme, instead of with buddypress-docs, although it could be both.

**Comment by JonathanReeve** [comment]
This one is going to be tough, it looks like. Even on a vanilla BuddyPress install and using the vanilla CBOX theme, commenting on new documents seems to be disabled.

**Comment by JonathanReeve** [comment]
There are a couple of threads on the BuddyPress forums about this, from a year ago. One might have a workaround:  https://buddypress.org/support/topic/comments-in-docs-are-closed-how-to-open/

**Comment by JonathanReeve** [comment]
So it looks like comments can be enabled from the admin view (Dashboard -> BuddyPress Docs -> select your document -> Edit -> check "Allow Comments"), but no word yet on how to make this default, or why it isn't already the default setting.

**Comment by JonathanReeve** [comment]
It looks like this is a WordPress setting. Since BuddyPress Docs are actually just a certain type of WordPress post, the global comment setting affects docs, too. This can be changed by checking Dashboard -> Settings -> Discussion -> Default Article Settings -> "Allow people to post comments on new articles," but that would also allow commenting on all new posts by default. Although I don't think there are any vanilla WP posts on the main Commons site that we'd have to worry about, and although I don't think commenting is enabled for non-members, I'm wary of flipping this switch, since I think it could potentially lead to more spam. I think the best thing to do is to add an option to the BuddyPress Docs admin panel that would allow admins to control whether users can comment on new docs by default--it could be called "Allow people to post comments on new docs," and it would override the global WordPress setting.

**Comment by JonathanReeve** [comment]
Other ideas for copy are welcome. 

![selection_498](https://cloud.githubusercontent.com/assets/1843676/6135489/1d340b70-b137-11e4-8797-04c5cfab2099.png)

**Comment by JonathanReeve** [comment]
Submitted this fix upstream at boonebgorges/buddypress-docs#440, and fixed locally on develop at 7ca73af. Should we hotfix this? It's kind of a new feature, but also kind of a bugfix for a serious-ish bug.

**Comment by terrainsvagues** [comment]
I would vote for hot-fixing.
