### ISSUE TITLE
504 gateway timeouts

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#226]
Probably a server issue rather than a theme issue. I just experienced this when posting a comment to a thread, and @terrainsvagues reports that a few users have seen this error when posting to forums.

**Comment by chriszarate** [comment]
Was it accompanied by a long (~30s) delay or was the error more or less immediate?

**Comment by JonathanReeve** [comment]
In my case there was a long delay, but Nicky says that there was a user that saw it immediately. Then again, the user also reported that it was a 404, so that is likely a different issue altogether.

**Comment by JonathanReeve** [comment]
We fixed this one, right? Closing.

**Comment by chriszarate** [comment]
Not completely. Mitigated with a faster SMTP relay, but still waiting on upstream fix to fork notifications to a separate PHP process. Sorry for not link the ticket her earlier.

https://github.com/boonebgorges/buddypress-group-email-subscription/issues/28

**Comment by chriszarate** [comment]
Closing as this is now a dupe of https://github.com/mlaa/commons/issues/12
