### ISSUE TITLE
Ninja Forms won't properly save > 60 form items

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#227]
@terrainsvagues reports that Ninja Forms isn't properly saving form items with IDs > 60 on a new test site. Ninja Forms help documents suggest editing some values in php.ini to fix this: 

http://docs.ninjaforms.com/article/202-long-form-saving-issue

Testing on dev.

**Comment by JonathanReeve** [comment]
I can't seem to reproduce this issue on my dev instance. However, editing the php config values as suggested doesn't seem to break anything that I can detect at the moment, so it might be worth a shot.

**Comment by chriszarate** [comment]
Suggest testing the values one at a time on prod. This feels icky.

**Comment by JonathanReeve** [comment]
Setting `max_input_vars` to 2000 seems to have fixed it, provisionally at least. @terrainsvagues, let me know if this acts up again and we can reopen this issue.
