### ISSUE TITLE
extended favorites plugin? 

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#228]
@kfitz notes the need for some kind of way to favorite blog posts or other items outside of the core Commons. BuddyPress already allows users to favorite posts, activity items, and maybe other things, but there doesn't seem to be a way to favorite group blog posts and things like that from within the network site.

**Comment by kfitz** [comment]
Just an added note: right now, one can revisit one's favorites in "My Commons" as a sub-item under Activity. It would be great to break the pan-Commons favorites out as a top-level menu item if we can.

**Comment by kfitz** [comment]
Resurfacing this site-wide favorites request: the more the Commons landing page comes to resemble a watched-activity feed, the more important favorites are likely to become, not just as a means of giving something a thumbs-up but as a means of following particular conversations or content and having updates, comments, etc appear in one's feed.

**Comment by susanasevilla** [comment]
Has been moved to our roadmap wiki page
