### ISSUE TITLE
rename "forum" to "discussion" in some slugs

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#230]
It looks like the old terminology for discussion areas, "forums," may still be found in the slugs: http://commons.mla.org/groups/test-group/forum/topic/a-very-very-long-test-post-2/.

**Comment by JonathanReeve** [comment]
I asked for help about this on [this post on the BuddyPress support forums](https://buddypress.org/support/topic/how-can-i-change-the-slug-for-forums/#post-238880), and it looks like there's a solution, but Ray brings up a good point about this--changing this slug will break the links in our activity stream. We could do a fancy find/replace using wp cli on the database to replace the slugs there, but then we're entering pretty dangerous territory. I wonder whether it might not be worth it to rename these slugs.

**Comment by JonathanReeve** [comment]
Let's talk about whether we need to do this. It's possible that the potential side-effects outweigh the benefits.

**Comment by modelm** [comment]
Internal link breakage could be alleviated by a regex redirect at the web server layer. That would allow time for search engines etc. to update their indexes and could remain in place once the database changes are made to ensure both URLs still work (the old URL should return a 301). Eventually the redirect could be removed if necessary (although I don't see a reason it would ever need to be).

**Comment by chriszarate** [comment]
I'd be in favor of not doing this.
