### ISSUE TITLE
send translations file out for copyediting

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#233]
With caveats that sometimes the context is not entirely clear from the code.

**Comment by JonathanReeve** [comment]
Marking this one for 3.0. Todo sub-steps:
 * [ ] make a list of all plugins and get `.pot` files for all 
 * [ ] ensure that the plugins are all loading their textdomains properly from `wp-content/languages` (this is no easy task)
 * [ ] provide context in some way? Associated screenshots? This would also be a fairly big task.

**Comment by chriszarate** [comment]
Closing individual ed. issue in favor of future periodic review.
