### ISSUE TITLE
activity greeting "What's new, Firstname?" only shows first word of first name

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#234]
If a user has a multi-word first name, the greeting at the top of /activity will only show the first name, unnecessarily splitting it into words. This sounds like a candidate for an upstream bug report, too.

**Comment by chriszarate** [comment]
This is also probably in the category of things that Editorial is not too keen on (aggressively casual salutation), so we could also address by rephrasing without a name.

**Comment by terrainsvagues** [comment]
Indeed! In fact a couple of users expressed concern with the implied casualness of the greeting when I was in Amherst. Didn't seem to fit with an academic social network to them.

**Comment by JonathanReeve** [comment]
Let's just trash this greeting altogether. Screenshot: 

![selection_037](https://cloud.githubusercontent.com/assets/1843676/8330626/9cc4edc8-1a50-11e5-846b-00b6c0a14fd8.jpg)
