### ISSUE TITLE
member usernames are generally difficult to find

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#237]
We've stripped out a lot of usernames from the UI, since they were cluttering up views like the member list, but messaging a non-contact requires you to enter their username, and usernames are not very easy to find. Usernames are available in the URL for the member (`/members/<username>`) and in the user's activity area (by clicking "view this member's Commons activity"), but this should probably be more obvious. 

Alternatively, we can see about making the autocomplete fields autocomplete anyone's names, and then we can eliminate much of the use-case for usernames.

**Comment by terrainsvagues** [comment]
I'd vote on trying to work around usernames, so that people could @mention, message, or invite someone by first name / last name

**Comment by JonathanReeve** [comment]
Yep, if we can get #268 working, then we wouldn't need usernames at all, really, except for login. Invite Anyone already autocompletes based on real names, as do @-mentions. I'll close this one is favor of #268.
