### ISSUE TITLE
Notification count in blue speech bubble at top displays "1" even when there are more notifications

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#239]
Confusing UI here. Since we have numbers in the notification bubble (and not just a notification bubble than turns blue when there are notifications), shouldn't that number correspond to the number of notifications?

**Comment by JonathanReeve** [comment]
With amazing synchronicity, I just opened a bug report about this, too. I'll migrate this one into #240, since I put the screenshot there.
