### ISSUE TITLE
notification counts in tabs and admin bar are divergent

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#240]
Has anyone else experienced this? 

![selection_512](https://cloud.githubusercontent.com/assets/1843676/6507064/8a34c672-c31d-11e4-845a-da677bf8cd62.png)

**Comment by JonathanReeve** [comment]
Apparently the answer is yes. @terrainsvagues reports: 

> Confusing UI here. Since we have numbers in the notification bubble (and not just a notification bubble than turns blue when there are notifications), shouldn't that number correspond to the number of notifications?

**Comment by JonathanReeve** [comment]
You're right, Nicky--the notifications are grouped by type: 

![selection_513](https://cloud.githubusercontent.com/assets/1843676/6508369/5abfaaca-c326-11e4-826b-0151be7852ea.png)

The admin bar count reads three, since that's one or more contact request, one or more mention, and one or more private message. 

It looks like that's the default behavior in Buddypress. There's [a section](https://github.com/buddypress/BuddyPress/blob/master/src/bp-notifications/bp-notifications-functions.php#L185) in `bp_notifications_get_notifications_for_user()` that reads: `Group notifications by component and component_action and provide totals`. However, if we agree that we want raw notification totals in the admin bar (that's my feeling, personally), I can easily switch this so that gets the raw count instead (5, in this example).

**Comment by JonathanReeve** [comment]
That was easy.

**Comment by terrainsvagues** [comment]
Argh! This issue persists. I had four notifications (I deleted two) but only a number one in the notifications admin bar. 
![screen shot 2015-03-13 at 9 10 50 am](https://cloud.githubusercontent.com/assets/7083891/6638915/f5805cb8-c960-11e4-96c9-908d563dc51d.png)

**Comment by terrainsvagues** [comment]
![screen shot 2015-03-16 at 8 48 00 am](https://cloud.githubusercontent.com/assets/7083891/6666476/2bc93928-cbbb-11e4-9243-0ce0430c303e.png)

**Comment by JonathanReeve** [comment]
This is fixed on develop, but the changes won't be apparent on the Commons until we release Sentimental. I typically close issues that are fixed on develop, just to keep track of what I've done, and what needs doing. We *could* adopt a model where we leave all bugs open that haven't merged into master, but that might get confusing if we use (as I do) the issue tracker as a kind of todo list--we might have to introduce a new waffle column for handling bugs that have been fixed but not yet deployed. I'd suggest we keep the current model of closing issues that are fixed on develop, and as a halfway measure, I can pull in all new changes to the test server *du jour*, like Sinclair, so they can be more widely testable there.

**Comment by chriszarate** [comment]
There's no milestone set here, which also might contribute to the confusion.
