### ISSUE TITLE
disable discussions search

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#241]
If you search on https://commons.mla.org/site-search/ and select "Discussions," you receive neither search results nor a "no items found" message. Instead, you are automatically redirected to commons.mla.org. Which is rather confusing.

**Comment by JonathanReeve** [comment]
Argh, this was broken, so I disabled it, but then I fixed it and reenabled it, but now it's broken again.

**Comment by JonathanReeve** [comment]
Something is terribly broken with this. I'll at least disable this search for now, in the hopes of fixing it later.

**Comment by JonathanReeve** [comment]
Disabled for now. Opened #254 for fixing this in a later release.
