### ISSUE TITLE
snippet functions and/or widgets break HTML when cutting mid-link

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#242]
The first of these two is being displayed as raw HTML. Why is the first link treated like this, but the second isn't? It might be that the snippet function cuts off the link in the middle, which makes it so that the HTML doesn't get recognized as such, because it doesn't close the quotes and angle brackets. Sounds like a candidate for an upstream bug report. 

![selection_518](https://cloud.githubusercontent.com/assets/1843676/6731592/3736af80-ce1c-11e4-80f6-f50b470b816b.png)

**Comment by chriszarate** [comment]
Fixing in `levitin`.
