### ISSUE TITLE
Members can private message anyone

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla#243]
Members can currently private message anyone, without limit, via standard BuddyPress functionality (contrary to their documentation). Is this desirable? Undesirable? How might we limit this? Options:

1. Members can only private message their contacts.
2. Members can private message anyone up to a limit of _n_ recipients.
3. Private messages are not a good conduit for conversation and we should investigate/encourage other mechanisms (facilitating e-mail, posting in group discussion forums with @-messages, etc.).

**Comment by chriszarate** [comment]
Light stats:
900 messages sent from 275 users
16 users have sent >10 messages

**Comment by JonathanReeve** [comment]
I agree with 3. I imagine that it might be nice to limit users to messaging, say, 5 other users at a time, and if they try to message more, presenting them with a message that suggests that they create a group. I see this something that we might be able to work out for 3.0.
