### ISSUE TITLE
time-stamp is off in notifications listing

### ISSUE THREAD

**Issue by kfitz** [mlaa/cbox-mla#244]
Notification time stamps are in an unknown time zone; these replies were actually posted 3 hours and X minutes ago.

![screen shot 2015-03-19 at 12 18 06 pm](https://cloud.githubusercontent.com/assets/3170201/6735073/35167698-ce32-11e4-933e-5b49d9834bb3.png)

**Comment by chriszarate** [comment]
Fixed.
