### ISSUE TITLE
Page <title> of /sites/ is "Site Directory Directory"

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla#245]
Obviously get rid of the extra "Directory".

What should the page be called? Just "Sites"? Should the in-page header match? Cf. Groups and Members. "Directory" does seem superfluous.

**Comment by JonathanReeve** [comment]
It looks like this is a pretty pervasive bug. It's even on BuddyPress's own site: https://buddypress.org/sites/. Filing this one upstream.

**Comment by JonathanReeve** [comment]
Filed https://buddypress.trac.wordpress.org/ticket/6339 upstream.

**Comment by kfitz** [comment]
That deserves a "whoa."
