### ISSUE TITLE
Invite Anyone: Strange member sorting

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla#246]
Low-priority: In the Invite Anyone tab, members are sorted in a strange order. First comes one or more sets of members in no discernible order, followed by the bulk of members in alphabetical order.

![member-sorting](https://cloud.githubusercontent.com/assets/739304/6790396/9d1d37ec-d17d-11e4-94da-472088b681aa.png)

**Comment by JonathanReeve** [comment]
I can live with this, for the time being, since I feel like it's going to be a non-trivial fix, and the idea is to get Sentimental out fairly quickly. If anyone disagrees, though, feel free to add this back to the Sentimental milestone.

**Comment by terrainsvagues** [comment]
Oh! I just realized that the ordering is the default order in Thoreau (by username). The people at the top of the list have numerical user names.

**Comment by JonathanReeve** [comment]
This was effectively fixed by removing this feature entirely.
