### ISSUE TITLE
personalized "dashboard" homepage? 

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#249]
Like CUNY's "My Commons." We already have a "My Commons," so would this just be a matter of redirecting to it on login?

**Comment by chriszarate** [comment]
This is more focused on personalized activity feeds, and would involve building on their codebase. Lots to uncover with storyboarding before getting started, though. Would this merge with our "My Commons" or stay separate?

**Comment by JonathanReeve** [comment]
I haven't seen CUNY's version--does it do much more than aggregate the activity feeds already available in our "My Commons"?

**Comment by chriszarate** [comment]
http://codex.commons.gc.cuny.edu/my-commons-2/

**Comment by JonathanReeve** [comment]
@terrainsvagues, if you're done with the wireframes for this page, I think you can close this one in favor of #312.
