### ISSUE TITLE
mobile app?

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#250]
According to @terrainsvagues, this is a feature much-requested from users.

**Comment by JonathanReeve** [comment]
As I understand it, most app stores tend to reject apps that just provide a user interface to a website.  But if there were features that used the mobile device's hardware, then it could potentially pass. So there'd need to be functions that used the phone's camera, microphone, accelerometer, gyroscope, GPS, or multitouch capabilities.

Pros: 
 * could provide users an easy way to upload convention photos
 * could provide location-aware features

Cons: 
 * would probably require writing it from scratch in Objective-C and/or Java, without taking advantage of any existing Commons code
 * would require a super non-trivial amount of time and developer resources

**Comment by chriszarate** [comment]
Agreed that a native app is out of reach. A mobile-first theme that implements touch UI patterns and provides a nice app icon for those that add it to their home screen is a reasonable target.

Worth noting that there are a number of native app frameworks that provide JavaScript APIs to device hardware. If we had a niche use case (e.g., some convention task as JR points out), we might consider building something super-simple to help people accomplish it on their mobile device.

Closing.
