### ISSUE TITLE
Provide clearer instructions for site customization at the moment of creation

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#253]
On https://commons.mla.org/sites/create/, link to a document describing how to customize a site in WP. Show this information on the "Congratulations! You have successfully registered a new site" page.

**Comment by JonathanReeve** [comment]
Good idea. Is there a document for that somewhere? I'll slate this for 3.0.

**Comment by terrainsvagues** [comment]
See #287

**Comment by terrainsvagues** [comment]
Task: investigate the In Site plug in for JS triggers that would facilitate this https://www.dudamobile.com/responsive-website/insite

**Comment by terrainsvagues** [comment]
In particular, rework wording on https://commons.mla.org/sites/create/
