### ISSUE TITLE
Automated avatar "badge" overlay?

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla#26]
Would it be possible to programmatically overlay the MLA Staff badge onto staff avatars? And could this be done in a way that would easily extend to other uses?

**Comment by chriszarate** [comment]
Investigate class attribute with `::after` pseudo-element with `background-image` and `z-index`. Class conditionally applied in PHP using status pulled from usermeta.

**Comment by modelm** [comment]
https://github.com/mlaa/levitin/commit/f1b427a97e426a4acf9223d866f814bf79e409ed
