### ISSUE TITLE
erroneous message "you successfully left the group" 

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#262]
To reproduce: 
 1. Visit one of your groups
 2. Click on a group tab, e.g. "Discussion" or "Activity" 
 3. Notice how you are greeted with a message saying "you successfully left the group," along with a button "Leave group," in seeming contradiction. 

This only seems to happen the first time you visit a group tab.

**Comment by JonathanReeve** [comment]
![selection_018](https://cloud.githubusercontent.com/assets/1843676/7460259/ace912be-f26f-11e4-9afe-ef45585a3ed9.jpg)

Hopefully this is because there's a disconnect between my user account and my superuser account.

**Comment by JonathanReeve** [comment]
Closing this, because it seems like it only affects me.

**Comment by chriszarate** [comment]
I saw this when browsing logged-out. I think Eric did, too.

**Comment by JonathanReeve** [comment]
That's no good. On what page?

**Comment by chriszarate** [comment]
On several groups, but most recently on "Nineteenth- and Early-Twentieth-Century German Literature," at about 3:28 p.m.

**Comment by JonathanReeve** [comment]
My guess is that these are groups that are getting synced, and lapsed members are getting removed from the groups. This message somehow gets triggered, then.

**Comment by terrainsvagues** [comment]
Just got this message when I posted to a group.
![screen shot 2015-05-05 at 1 32 15 pm](https://cloud.githubusercontent.com/assets/7083891/7478811/48f329e0-f32b-11e4-8b60-acc10a548c1c.png)

**Comment by JonathanReeve** [comment]
What's strange is that I can reproduce this pretty easily on production, just by opening lots of group pages, but I can't seem to reproduce this on Dickenson, whether logged in or logged out. If anyone has any ideas as to what could be causing this, please let me know.

**Comment by JonathanReeve** [comment]
Ok, I think I fixed this one in mlaa/cbox-mla@c727dad. If it reappears at all, please let me know and/or reopen this issue.
