### ISSUE TITLE
Viewing "My Contacts" from /activity shows activity for all users, not just my contacts

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#266]
Go to https://commons.mla.org/activity/ and click "My Contacts." The activity stream does not change to reflect your contacts.

**Comment by JonathanReeve** [comment]
So @rekmla says this is mlaa/humcore#4. It looks like humcore handling of activities is causing this and other activity-related issues. Closing this as a duplicate of that one.
