### ISSUE TITLE
can't save email subscription option "no email" from group settings page

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#270]
Spawned from #269.

**Comment by kfitz** [comment]
I'm a little puzzled by the move of this issue. What I was trying to do was to change my committee's default email setting from "daily digest" to "all mail." Will this fix solve that use case?

**Comment by JonathanReeve** [comment]
Your issue is fixed on dev, but this is another issue that I discovered in the process of fixing yours. The buddypress-group-email-subscription plugin isn't prepared to handle default default subscription values other than "no email." We should probably ship the fix for this one along with the fix to #269, so that setting default subscription levels works as expected for all values.
