### ISSUE TITLE
topic status options when creating new topic

### ISSUE THREAD

**Issue by kshkim** [mlaa/cbox-mla#271]
group > discussion > new topic > topic status: pending 

When I try to create a new topic with the topic status "pending," it sends me back to the most recent topic post. (I'm assuming "spam" and "trash" send them to their proper locations, since I've tried it out and it's not in the discussion board, but it's also strange that those are options.) 

![screen shot 2015-05-26 at 3 37 13 pm](https://cloud.githubusercontent.com/assets/8835589/7821503/25a0fe66-03bd-11e5-939c-64130f2b4ad6.png)

**Comment by JonathanReeve** [comment]
This is a feature, actually. A pending topic is one that needs moderator approval before it can be posted, which explains why you're not seeing it in the discussion board. It appears in the admin panel, however, (`/wp-admin/`) under Topics. You get redirected to the most recent topic, since the pending topic is not made public.

**Comment by terrainsvagues** [comment]
Shouldn't we message something more useful to the user, though? This feature is sporting bug garb.

**Comment by JonathanReeve** [comment]
The user in this case is mods and above. So we could add a message, but I'm guessing it'd mostly be displayed to you and Katherine. Is there a use-case for creating pending topics?

**Comment by terrainsvagues** [comment]
Yes, Annie tried to do it and couldn't work out where her message had gone. She is a moderator for a committee but wanted to have someone review her post first.

**Comment by JonathanReeve** [comment]
By "mod and above" I mean those with the WordPress role "moderator," "administrator," or "super-admin," which is only our staff. Group admins like committee officers won't see this option, so they won't have this problem.

**Comment by chriszarate** [comment]
Group admins do see this option, as reported above. I think you are confusing WP roles with bbPress roles (which BP manages in group contexts).

**Comment by JonathanReeve** [comment]
Ah, right you are. Yet this is still the default and expected behavior. Is the issue that we aren't really using moderators (those with the WordPress role) to moderate topics, so that the concept of a pending topic is not very useful?

**Comment by chriszarate** [comment]
Let's discuss at the next meeting whether this is useful enough to enhance with better messaging or whether it should just be disabled.
