### ISSUE TITLE
roll our own select boxes? 

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#275]
`<select>` dropdown menus look different across browsers and operating systems. They can often clash with the style of a web page. To solve this problem, there are [some JS / jQuery libraries](https://github.com/select2/select2) that can allow for styling dropdowns. Disadvantages are that they aren't handled as natively on mobile OSes, and that this adds a new layer of complexity. But they're very pretty--see [the select2 demo](https://select2.github.io/examples.html).

**Comment by chriszarate** [comment]
File against boilerplate?

Can probably exclude mobile with feature detection.

**Comment by JonathanReeve** [comment]
Good idea. I'll add it there, as well.
