### ISSUE TITLE
replace contacts with following?

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#278]
There's [a script](https://github.com/r-a-y/buddypress-followers/wiki/Convert-friends-over-to-followers) that can convert friends / contacts to mutual followers. We would need to hide "add contact" buttons and instead feature "follow" buttons. "Show this field only to my contacts" might need to be "show this field only to those I'm following." There might also be some other privacy implications here. But this would simplify things quite a bit, and avoid confusion around contacts / followers, which don't often exist in the same social networks, in my experience.

**Comment by JonathanReeve** [comment]
This looks like the plugin to use: https://github.com/r-a-y/buddypress-followers/wiki

**Comment by terrainsvagues** [comment]
See #286
