### ISSUE TITLE
add profile completeness progress bar?

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#279]
It'd be fun to have a profile completeness bar on the portfolio edit screen, to encourage new users to fill out their portfolios, upload avatars, and so on. This sounds like it would be need to be a plugin.

**Comment by JonathanReeve** [comment]
Looks like [a plugin exists](https://wordpress.org/plugins/buddypress-profile-progression/).

**Comment by terrainsvagues** [comment]
See #288

**Comment by JonathanReeve** [comment]
The plugin seems to work, although it will take some tweaking. The next questions here are: what portfolio fields do we want to be part of the completeness criteria, and how should they be weighted? Avatar and academic interests would make sense, but we can't force users to get Twitter accounts or blogs, and users might not necessarily have publications or even a (traditional) educational history, so it could be off-putting to require those fields to be filled. 

If we're only tracking two profile fields, it might not be worth it to add the progress bar, since it will add overhead and maintenance costs to the stack.
