### ISSUE TITLE
remove redundant directory titles?

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#283]
Currently, the user's location among directories (top-level sections) is indicated by both the top-level nav links and the section heading: 

![selection_026](https://cloud.githubusercontent.com/assets/1843676/7936992/27fcb968-090b-11e5-9425-5bdcbf977764.jpg)

If we make the top-level nav a little bigger, or find some other kind of breadcrumb solution (see #222) we can avoid this doubling.

**Comment by chriszarate** [comment]
Members (section) !== Members directory

Context-aware navigation of this type usually indicates when you are in the contours of a section, not at its organizational apex. There are many other pages under each section that are not the directory and therefore need a page title. It could be visually jarring to remove the title for only one of those pages—but this depends on design implementation.

Perhaps the page title could be shortened to just "Directory," but I believe we discussed that before and decided against it.

**Comment by JonathanReeve** [comment]
True. But if the hierarchy were more apparent than our current hierarchy, this would make more sense. I imagine there could be a two-tiered primary/secondary nav like this: 
 
    Groups | Members | Sites | Activity | ... 
            ---------

    All | I'm Following | Following Me 

If it can be implemented in a design that conveys it well, "Members -> All" might be simpler than, and still convey the same meaning as, "Members -> Members Directory -> All Members." 

This wouldn't be for just the Members Directory, though, but for all directories.

**Comment by terrainsvagues** [comment]
Let's talk about this this morning. I'm into the simplicity implied by removing the extra step.

**Comment by chriszarate** [comment]
Closing in favor of work done in `levitin`.
