### ISSUE TITLE
hide "reply" buttons on forum posts

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#284]
As @terrainsvagues points out, these could give the mistaken impression that forum topics are infinitely hierarchical. 

![selection_028](https://cloud.githubusercontent.com/assets/1843676/7943173/e9819d9a-0930-11e5-8a2d-5787e1b7f257.jpg)

**Comment by modelm** [comment]
<img width="839" alt="screen shot 2015-10-13 at 2 41 04 pm" src="https://cloud.githubusercontent.com/assets/330857/10464608/b53b2df8-71b8-11e5-8dbe-313ddd4658a2.png">

This looks like it's already done, closing.
