### ISSUE TITLE
Get Rid of Docs

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#289]
We've mentioned that we might need to let something go in the move to 3.0, and this would be that something.

**Comment by JonathanReeve** [comment]
I'm always in favor of simplifying, but someone should come up with a plan for what to do about the 139 existing docs.

**Comment by terrainsvagues** [comment]
I would suggest converting them to files. But I also agree with @chriszarate's assertion that we need to provide some kind of collaborative authoring for our members. There are those that use it—and many more probably would if it was more user friendly. OR could we track Buddy Press Docs in the activity stream?

**Comment by JonathanReeve** [comment]
I could probably write something to convert docs to files. They would no longer be editable, of course. 

We track BuddyPress Docs in the activity stream already. Not a whole lot of activity there, though.
