### ISSUE TITLE
allow site admins to change site avatars?

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#293]
I've been testing [the plugin Blog Avatar](https://github.com/buddydev/blog-avatar), which seems to be working nicely. It provides a new admin setting, Dashboard -> Settings -> Blog Avatar, where site admins can change their site's avatar. 

This is an extension of #116, which addressed confusion surrounding the site creator's avatar when used as a blog avatar. 

Ideally, this would be a step in site creation, and not just a dashboard admin setting.

**Comment by modelm** [comment]
bp-blog-avatar activated on foer.mlacommons.org
