### ISSUE TITLE
get group directory to listen to GET requests like `/groups?type=forum`

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#298]
This will allow us to have URLs associated with certain group directory tabs. 

Alternatively, we could use hashes: `/groups#forums`. This might allow for better AJAX integration.

**Comment by chriszarate** [comment]
Let's stick with query strings, which are much less complicated than hashes and hash-bangs—especially when it comes to playing nice with Google et al. We can fill in gaps with the History API if we need to. Let's talk about overall strategy here.

**Comment by JonathanReeve** [comment]
What works: 
 * PHP listens to $_GET parameters, such that navigating cold to http://my-vm/groups/?type=committees correctly takes you to the committees page. 
 * JS sets the URL after filtering groups with AJAX, such that clicking "committees" changes the url to http://my-vm/groups/?type=committees. 
 * Clicking to anther page from Committees, and then clicking the browser "back" button changes the URL back to http://my-vm/groups/?type=committees. 

What doesn't work yet: 
 * Although clicking "back" changes the URL, and although PHP can interpret those URLs when cold-visited, clicking "back" doesn't take you to the properly filtered page, so you can go back from, say, http://my-vm/groups/?type=forums to http://my-vm/groups?type=committees, but you won't see a list of committees.

**Comment by chriszarate** [comment]
You're pushing state into the History API, so you just need to listen for `popstate`. Something like this should work:

```javascript
jq(window).on('popstate', function () {
  // do stuff with window.location.search
});
```
