### ISSUE TITLE
topic pagination summary is a little wordy

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#300]
A list of discussion topics is usually followed by a pagination-area line that says something like: "Viewing 6 topics - 1 through 6 (of 6 total)." This is a little wordy for a single page. We don't need to be told that we're viewing six topics when we can see all six topics. 

I think we should hide this line if we're not showing pagination buttons, and if we are, this line could read something like "Viewing posts 11-15 of 30 total."

**Comment by chriszarate** [comment]
I'd prefer a count indicator next a topics head, e.g.:

Topics  [ 30 ]

Then pagination links, with page indicator, could be shown or hidden conditionally. No other indicators or counts needed.

**Comment by JonathanReeve** [comment]
Good idea. Let's just get rid of that line entirely.
