### ISSUE TITLE
Files: archive button for admins

### ISSUE THREAD

**Issue by kshkim** [mlaa/cbox-mla#308]
For committee work that needs to be private: could we have a button that archives/hides files?

**Comment by JonathanReeve** [comment]
Would this be a button to make files visible only to other group admins?

**Comment by kshkim** [comment]
Yep. Since this is only useful to a handful of people, should this just be tagged as a wishlist item?

**Comment by JonathanReeve** [comment]
I don't know for sure, but it seems that BuddyDrive might be able to handle this in some way, whether through its visibility property or its trash function (which could be rebranded as "archive"). This might be another point in that direction.
