### ISSUE TITLE
Discussion, topic post: trash button

### ISSUE THREAD

**Issue by kshkim** [mlaa/cbox-mla#309]
Question: Where does the trash go? (And can one un-trash an item?)

Could we have a notification that pops up to confirm that you would like to delete a discussion topic?

**Comment by JonathanReeve** [comment]
They're in Dashboard -> Topics -> Trash. For me, when I click "trash" on a topic, the "trash" button changes to a button that says "restore." Does that happen for you?

**Comment by kshkim** [comment]
Can all members do that (in case they want to restore their trashed item)?

**Comment by JonathanReeve** [comment]
Non-admin members don't have access to the dashboard. But they also don't have the ability to trash discussion topics. Group admins have the ability to trash and immediately restore discussion topics, I believe.
