### ISSUE TITLE
rename Activity?

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/cbox-mla#310]

**Comment by terrainsvagues** [comment]
I didn't think we'd agreed to call this home? I'm still interested in discussing activity being 'my commons' and renaming the latter, per our conversation this morning.

**Comment by JonathanReeve** [comment]
Ok. But what will this page be called when the user is logged out?

**Comment by terrainsvagues** [comment]
We can work through that in tomorrow's meeting. I just don't think we should be defining (and closing) issues that haven't been agreed upon by product and dev.

**Comment by JonathanReeve** [comment]
Ok. I'd thought this part was already decided, but it's easy to revert and reopen.

**Comment by JonathanReeve** [comment]
Calling this "Dashboard" for the moment. "Activity" remains at the url `/activity`, but is not linked in the top-level nav. We can change this later, if we want.
