### ISSUE TITLE
Site visibility is not respected in "Sites" listing

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#328]
To reproduce:

Go to https://exhaustfumes.commons.mla.org/wp-admin/options-reading.php and verify that the author has the blog set to "Visible only to registered users of this network."
Then, while logged in, go to https://commons.mla.org/sites/ and look for her site. 
It's not there!
Order alphabetically.
It's still not there!

She would like it to be discoverable to MLA members but not to admins. It _does_ show up in "Activity" and in "Recent posts" on the front page, but not in "Sites."

**Comment by chriszarate** [comment]
@modelm Is this fixed in levitin?

**Comment by modelm** [comment]
Not fixed in levitin. I'll take a look.

**Comment by terrainsvagues** [comment]
Any update on this? The author e-mailed again yesterday and wants to know that her work will be visible in the "sites" listing to logged-in members, because if not she doesn't see the point of using the Commons.

**Comment by modelm** [comment]
Fixed in levitin by f83000a.
