### ISSUE TITLE
Single profile/portfolio page

### ISSUE THREAD

**Issue by terrainsvagues** [mlaa/cbox-mla#337]
Members find our current profile/portfolio distinction. I propose we create a single profile page that shows member information, photo, CORE publications, recent activity, and connections.

**Comment by modelm** [comment]
Single profile page will include:

* portfolio
* groups
* sites (only ones they have author/contributor status or above)
* deposits
* forum post activity

focus on authorship for activity that we do show

maximize signal to noise wrt direct authorship

**Comment by modelm** [comment]
Waiting on wireframe to finish layout.

**Comment by terrainsvagues** [comment]
https://wireframe.cc/N2rk3B
