### ISSUE TITLE
Allow "mark all as read" action for notifications

### ISSUE THREAD

**Issue by chriszarate** [mlaa/cbox-mla#41]
I have a lot of notifications. I want to mark them all as read. This might be targeted upstream at CBOX core.

![screen shot 2014-06-26 at 9 14 56 am](https://cloud.githubusercontent.com/assets/739304/3398741/1526d668-fd34-11e3-8496-78e12e8dcd27.png)

**Comment by JonathanReeve** [comment]
This was fairly complicated, as I recall, so I'll put this off until Sentimental.

**Comment by JonathanReeve** [comment]
This was super complicated, and as an enhancement, this might be something better suited for 3.0.
